CREATE TABLE IF NOT EXISTS credentials (
  id BIGINT UNSIGNED AUTO_INCREMENT COMMENT "ID",
  password TEXT NOT NULL COMMENT "パスワード",
  created_at DATETIME (6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT "作成日",
  updated_at DATETIME (6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT "更新日",
  PRIMARY KEY (id)
);
