CREATE TABLE IF NOT EXISTS files (
  id BIGINT UNSIGNED AUTO_INCREMENT COMMENT "ID",
  folder_id BIGINT UNSIGNED NOT NULL COMMENT "フォルダID",
  name VARCHAR(128) NOT NULL COMMENT "ファイル名",
  path VARCHAR(255) NOT NULL COMMENT "ファイルパス",
  mime_type VARCHAR(64) NOT NULL COMMENT "MIMEタイプ",
  is_hide TINYINT (1) NOT NULL DEFAULT 0 COMMENT "非表示フラグ",
  created_at DATETIME (6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT "作成日",
  updated_at DATETIME (6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT "更新日",
  deleted_at DATETIME (6) COMMENT "削除日",
  PRIMARY KEY (id),
  CONSTRAINT fk_files_folder_id FOREIGN KEY (folder_id) REFERENCES folders (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT uq_files_path UNIQUE (path)
);
