CREATE TABLE IF NOT EXISTS folders (
  id BIGINT AUTO_INCREMENT COMMENT "ID",
  folder_id BIGINT COMMENT "フォルダID",
  name VARCHAR(128) NOT NULL COMMENT "フォルダ名",
  path VARCHAR(255) NOT NULL COMMENT "フォルダパス",
  is_hide TINYINT (1) NOT NULL DEFAULT 0 COMMENT "非表示フラグ",
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT "作成日",
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT "更新日",
  deleted_at TIMESTAMP(6) COMMENT "削除日",
  PRIMARY KEY (id),
  CONSTRAINT fk_folders_folder_id FOREIGN KEY (folder_id) REFERENCES folders (id)
);
