// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/api/usecase/folder.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	dto "file-server/internal/app/api/usecase/dto"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFolderUsecase is a mock of FolderUsecase interface.
type MockFolderUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockFolderUsecaseMockRecorder
}

// MockFolderUsecaseMockRecorder is the mock recorder for MockFolderUsecase.
type MockFolderUsecaseMockRecorder struct {
	mock *MockFolderUsecase
}

// NewMockFolderUsecase creates a new mock instance.
func NewMockFolderUsecase(ctrl *gomock.Controller) *MockFolderUsecase {
	mock := &MockFolderUsecase{ctrl: ctrl}
	mock.recorder = &MockFolderUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFolderUsecase) EXPECT() *MockFolderUsecaseMockRecorder {
	return m.recorder
}

// Copy mocks base method.
func (m *MockFolderUsecase) Copy(arg0, arg1 uint64, arg2 bool) (*dto.FolderInfoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", arg0, arg1, arg2)
	ret0, _ := ret[0].(*dto.FolderInfoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Copy indicates an expected call of Copy.
func (mr *MockFolderUsecaseMockRecorder) Copy(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockFolderUsecase)(nil).Copy), arg0, arg1, arg2)
}

// Create mocks base method.
func (m *MockFolderUsecase) Create(arg0 uint64, arg1 string, arg2 bool) (*dto.FolderInfoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(*dto.FolderInfoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFolderUsecaseMockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFolderUsecase)(nil).Create), arg0, arg1, arg2)
}

// FindOne mocks base method.
func (m *MockFolderUsecase) FindOne(arg0 string, arg1 bool) (*dto.FolderInfoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", arg0, arg1)
	ret0, _ := ret[0].(*dto.FolderInfoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockFolderUsecaseMockRecorder) FindOne(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockFolderUsecase)(nil).FindOne), arg0, arg1)
}

// Move mocks base method.
func (m *MockFolderUsecase) Move(arg0, arg1 uint64, arg2 bool) (*dto.FolderInfoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Move", arg0, arg1, arg2)
	ret0, _ := ret[0].(*dto.FolderInfoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Move indicates an expected call of Move.
func (mr *MockFolderUsecaseMockRecorder) Move(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Move", reflect.TypeOf((*MockFolderUsecase)(nil).Move), arg0, arg1, arg2)
}

// Read mocks base method.
func (m *MockFolderUsecase) Read(arg0 uint64, arg1 bool) (*dto.FolderBodyDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0, arg1)
	ret0, _ := ret[0].(*dto.FolderBodyDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockFolderUsecaseMockRecorder) Read(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockFolderUsecase)(nil).Read), arg0, arg1)
}

// Remove mocks base method.
func (m *MockFolderUsecase) Remove(arg0 uint64, arg1 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockFolderUsecaseMockRecorder) Remove(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockFolderUsecase)(nil).Remove), arg0, arg1)
}

// Update mocks base method.
func (m *MockFolderUsecase) Update(arg0 uint64, arg1 string, arg2, arg3 bool) (*dto.FolderInfoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*dto.FolderInfoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockFolderUsecaseMockRecorder) Update(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFolderUsecase)(nil).Update), arg0, arg1, arg2, arg3)
}
