services:
  db:
    image: mysql:9.0
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: develop
      MYSQL_PASSWORD: develop
      MYSQL_DATABASE: develop
      TZ: UTC

  api:
    build:
      context: ./build/package
      dockerfile: Dockerfile.local
    volumes:
      - .:/workspace/api
      - db_data:/workspace/api/db/data
    working_dir: /workspace/api
    ports:
      - 8000:8000
    tty: true
    depends_on:
      - db

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db_data:
