name: Deploy api to GitHub Container registry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Login to GitHub Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: build/package/Dockerfile.deploy
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/file-server:latest
            ghcr.io/${{ github.repository_owner }}/file-server:1.0.0
